### ISSUE TITLE
Can you make auto click on button autdio on your extension?

### ISSUE THREAD

**Issue by xxx-yyy-zzz** [shirshak55/scrapper-tools#1]
it not working :(

window.onload=function(){
 setInterval(autoClick,100);
 }
 function autoClick(){
  if(document.getElementById("solver-button") !== null){

  document.getElementById("solver-button").click();
 }
}

**Comment by shirshak55** [comment]
can u please elaborate?

Did u ran it on evaluate script?

**Comment by xxx-yyy-zzz** [comment]
i use tampermonkey extension! i want auto click solver-button, help me, thanks you!
https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo

**Comment by shirshak55** [comment]
did u ran it from console.
```
window.onload=function(){
setInterval(autoClick,100);
}
function autoClick(){
if(document.getElementById("solver-button") !== null){

document.getElementById("solver-button").click();
}
}
```
It should give u more information.

**Comment by shirshak55** [comment]
if any problem reopen
